version: '3'

vars:
  BINARY: dex
  BUILD_DIR: ./bin

tasks:
  build:
    desc: Build the dex binary to ./bin/
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/{{.BINARY}} ./cmd/dex
    sources:
      - ./**/*.go
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY}}"

  install:
    desc: Install dex to $GOPATH/bin
    cmds:
      - go install ./cmd/dex

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}

  default:
    desc: Build the binary
    deps: [build]
